### ISSUE TITLE
Feature: Change Wallpaper

### ISSUE THREAD

**Issue by janschoepke** [zehfernandes/pliim#10]
It would be nice, if the app could change the wallpaper to a preselected one or a specific color.

**Comment by zehfernandes** [comment]
That's an excellent an idea.
I will implement soon :)

**Comment by zehfernandes** [comment]
Check the new version https://github.com/zehfernandes/pliim/releases/tag/v1.3.0

**Comment by joshuapinter** [comment]
Hi @zehfernandes, the latest version does change the wallpaper but it doesn't change to a specified one or anything. For example, I have a folder of car pictures that I cycle through automatically. What I would like is to change it to a default macOS wallpaper when I turn on Pliim. 

What do you think?

**Comment by zehfernandes** [comment]
Hi, @joshuapinter you are right. I will think in a way to do that :)

**Comment by joshuapinter** [comment]
@zehfernandes Excellent! Thanks. Yeah, basically I'd rather not have sick pics of Porsches when I'm giving a Powerpoint presentation. :) 

Maybe just allowing you to set a specific wallpaper (or file) to change to would be enough. You could store it in Pliim or just reference a specific wallpaper and just handle when/if that wallpaper file is deleted or moved.

**Comment by zehfernandes** [comment]
@joshuapinter Done! Now you can choose a specific wallpaper in Preferences `right-click in the icon:`
https://github.com/zehfernandes/pliim/releases/tag/v1.5.0

**Comment by joshuapinter** [comment]
Boom!

Does Pliim have an auto-update?

**Comment by zehfernandes** [comment]
unfortunately not. (it's not a signed app)
I recommend download and replace for the new version

**Comment by joshuapinter** [comment]
Hmm, trying out 1.5.0 but it doesn't seem to change to the default black screen or the one I've selected.

**Comment by zehfernandes** [comment]
@joshuapinter weird. Do you download the .zip? I test here, and everything seems fine. Do you close the app and replace? Can you check the version in the about?

**Comment by joshuapinter** [comment]
Yes and it's 1.5.0.

I have my wallpaper to cycle through a folder and whenever I turn on Pliim (even in the latest version), it just cycles to a different wallpaper in that same directory. It doesn't set it to the black wallpaper or to the one that I specified. It's tough to show this happening in a screen cast but that's what's happening.

**Comment by zehfernandes** [comment]
@joshuapinter I will try to simulate this scenario and come back with an answer.

**Comment by phldgmn** [comment]
+1 – have the exact same issue. It works if I have a stock wallpaper selected by default. But as soon as I select a folder for my wallpapers to cycle through, pliim just cycles to another wallpaper instead of using the black color.

**Comment by sparvaneh** [comment]
My background stays Black color, and I can't change it even after disabling Pliim. Is there any way to solve the issue.
