### ISSUE TITLE
Broken main window display

### ISSUE THREAD

**Issue by GregOriol** [zehfernandes/pliim#12]
I don't know if it's me, but the main window is currently very much broken:
<img width="585" alt="capture d ecran 2018-05-31 a 13 37 34" src="https://user-images.githubusercontent.com/3975044/40780212-df1ba534-64d7-11e8-85ca-a3a9cdd4054e.png">

Pliim 1.4.0
macOS 10.13.4

**Comment by zehfernandes** [comment]
Hello @GregOriol 

Work fine for me. 
Try to quit the app and open again.

**Comment by GregOriol** [comment]
I tried (obviously), still the same display problem.
