### ISSUE TITLE
"Disable notifications" works, but does not enable notifications when leaving presentation mdoe

### ISSUE THREAD

**Issue by phldgmn** [zehfernandes/pliim#15]
When enabling the setting "disable notifications", notifications are disabled as soon as I enter the presentation mode, but upon leaving presentation mode, the notifications stay disabled and I have to manually enable notifications again.

**Comment by zehfernandes** [comment]
Hi @pdiegmann 

What is the version of your apple system?

**Comment by phldgmn** [comment]
Hi @zehfernandes,
it was High Sierra, 10.13.6.
I tried it just now on Mojave, 10.14, and there it does not mute the notifications in the first place.
