### ISSUE TITLE
Auto-hide apps didn't work in Mojave 10.14

### ISSUE THREAD

**Issue by voodoo6** [zehfernandes/pliim#16]
Hi, would be great if Plimm could auto-hide all open apps when its switched off – current behavior requires me to command-H every one of my open apps when I turn off Plimm..

Great little app – thanks!

**Comment by zehfernandes** [comment]
Hi @voodoo6 Pllim already do that.

What version of the app you have? And what is the version of your apple system?

**Comment by voodoo6** [comment]
Hi,

I just checked - it was an older version, just upgraded to 1.5.0 and now Plimm doesn’t seem to hide the active apps when the switch is flicked – desktop icons disappear but the open apps remain visible. Using Mojave 10.14..

Thanks,
Matt

**Comment by zehfernandes** [comment]
Oh! I got it.
I didn't test with Mojave yet.

I will try to fix this bug soon.
