### ISSUE TITLE
Desktop icons now missing

### ISSUE THREAD

**Issue by sbuys** [zehfernandes/pliim#18]
With latest version 1.6 I cannot get my desktop back to default state. With pliim out of presentation mode and even after reset I cannot get back to my desktop icons.

**Comment by sbuys** [comment]
`defaults write com.apple.finder CreateDesktop -bool true;killall Finder`

in terminal fixes.

**Comment by zehfernandes** [comment]
Hi, @sbuys probably you click to fast in enable and disable.
Can you try again and see if the error persist? 

Same issue/solution: 
https://github.com/zehfernandes/pliim/issues/2
