### ISSUE TITLE
downloaded, uninstalled... now i dont have any icons on my desktop

### ISSUE THREAD

**Issue by lostmonster** [zehfernandes/pliim#2]
how might I show my desktop icons, now that i've uninstalled this software?

**Comment by zehfernandes** [comment]
Hey @lostmonster.

You can try turn on the presentation mode, wait a little bit and turn off the presentation mode again. 


If you stucked without the app run the following command in your terminal:

```
defaults write com.apple.finder CreateDesktop -bool true; killall Finder
```

and your desktop will be available again.
