### ISSUE TITLE
Hide Icons only applies to primary desktop

### ISSUE THREAD

**Issue by psayre23** [zehfernandes/pliim#20]
I have multiple monitors setup on my mac. When I enable presentation mode, only the icons on my primary desktop are hidden; not all of my desktops. 

Pliim Version: 1.0 (Setapp)
Device: MacBook Pro (2017)
Mac Version: 10.15.6

**Comment by zehfernandes** [comment]
Hi @psayre23 ,

I released a new version of PliimPRO today to support multiple monitors. ✨
Check the updates in the Setapp store.

Thanks
