### ISSUE TITLE
Missing a way to close the app

### ISSUE THREAD

**Issue by nagueva** [zehfernandes/pliim#4]
I accidentally opened two instances of the app and realize that we don't have a way to close it.

Of course we can do it by command line or activity monitor but would be great to have a way to quit the app in a friendly way.

**Comment by zehfernandes** [comment]
Fixed the issue of two app instances. https://github.com/zehfernandes/pliim/commit/6c2a10f675b822ead5f361a33119fe617cfdd2e3

And now you can quit the app using the shortcut `command+q` or with the right-click in the icon:

![screen shot 2017-11-26 at 17 49 26](https://user-images.githubusercontent.com/1891339/33243703-2eed64fa-d2d2-11e7-94a1-181d5ec89146.png)


v1.2.0 available 
https://github.com/zehfernandes/pliim/releases/tag/v1.2.0

🎉
