### ISSUE TITLE
O ícone poderia mudar quando o pliim for ativado

### ISSUE THREAD

**Issue by lbebber** [zehfernandes/pliim#5]
Atualmente o ícone ta transparente normalmente—poderia ficar com 100% de opacidade quando o pliim estiver ativo. (Na real imagino que essa era a intenção mas não está funcionando, é isso?)

(Na verdade mesmo me da um pouco de TOC o icone ser o único meio transparente da minha barrinha do mac, hahah. Sugiro ter 2 shapes pro ícone, um para ligado, outro para desligado.)

**Comment by zehfernandes** [comment]
Valeu @lbebber 

fixed https://github.com/zehfernandes/pliim/commit/879edd5c933b8b6d2a0fe7d5470dc6da848ca662 https://github.com/zehfernandes/pliim/commit/378934e0536e6ddaee580d65922b03a338a551b9

Versão 1.2.0 já disponível
https://github.com/zehfernandes/pliim/releases/tag/v1.2.0

🎉
