### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by xcrap** [zehfernandes/pliim#9]
Is there any uninstall procedure we should de aware of ?

After removing pliim my dock don't hide anymore. I've tried to reset system preferences and everything but it still doesn't work. Also when I uninstalled the desktop icons where gone after uninstalling they didn't returned. I runned the app again to show desktop icons before removing it from the second time.

I wonder if there is a way to reset the settings before the software was runned because it messed with my dock.

**Comment by zehfernandes** [comment]
hi @xcrap 

check issue https://github.com/zehfernandes/pliim/issues/2
